#!/bin/bash
echo "=== BACKEND IMPORT FILES VERIFICATION ==="
echo ""
echo "✓ Models:"
ls -lh app/Models/ImportLog.php 2>/dev/null && echo "  ✓ ImportLog.php" || echo "  ✗ ImportLog.php MISSING"
echo ""
echo "✓ Migrations:"
ls -lh database/migrations/2026_03_31_115445_create_import_logs_table.php 2>/dev/null && echo "  ✓ create_import_logs_table.php" || echo "  ✗ MISSING"
echo ""
echo "✓ Imports:"
ls -lh app/Imports/JobDescriptionImport.php 2>/dev/null && echo "  ✓ JobDescriptionImport.php" || echo "  ✗ MISSING"
echo ""
echo "✓ Jobs:"
ls -lh app/Jobs/ImportJobDescriptionsJob.php 2>/dev/null && echo "  ✓ ImportJobDescriptionsJob.php" || echo "  ✗ MISSING"
echo ""
echo "✓ Controllers:"
ls -lh app/Http/Controllers/Api/JobDescriptionImportController.php 2>/dev/null && echo "  ✓ JobDescriptionImportController.php" || echo "  ✗ MISSING"
echo ""
echo "✓ Requests:"
ls -lh app/Http/Requests/JobDescriptionImportRequest.php 2>/dev/null && echo "  ✓ JobDescriptionImportRequest.php" || echo "  ✗ MISSING"
echo ""
echo "✓ Services:"
ls -lh app/Services/JobDescriptionTemplateService.php 2>/dev/null && echo "  ✓ JobDescriptionTemplateService.php" || echo "  ✗ MISSING"
echo ""
echo "✓ Exports (Template):"
ls -lh app/Exports/JobDescriptionTemplate*.php 2>/dev/null | wc -l | xargs -I {} echo "  ✓ {} template export files"
echo ""
echo "✓ Notifications:"
ls -lh app/Notifications/ImportJobDescriptionCompletedNotification.php 2>/dev/null && echo "  ✓ ImportJobDescriptionCompletedNotification.php" || echo "  ✗ MISSING"
echo ""
echo "✓ Routes:"
php artisan route:list --path=job-descriptions/import 2>/dev/null | grep -c "JobDescriptionImportController" | xargs -I {} echo "  ✓ {} import routes registered"
echo ""
echo "=== SYNTAX VALIDATION ==="
php -l app/Models/ImportLog.php 2>&1 | grep -q "No syntax errors" && echo "  ✓ ImportLog.php" || echo "  ✗ ImportLog.php"
php -l app/Imports/JobDescriptionImport.php 2>&1 | grep -q "No syntax errors" && echo "  ✓ JobDescriptionImport.php" || echo "  ✗ JobDescriptionImport.php"
php -l app/Jobs/ImportJobDescriptionsJob.php 2>&1 | grep -q "No syntax errors" && echo "  ✓ ImportJobDescriptionsJob.php" || echo "  ✗ ImportJobDescriptionsJob.php"
php -l app/Http/Controllers/Api/JobDescriptionImportController.php 2>&1 | grep -q "No syntax errors" && echo "  ✓ JobDescriptionImportController.php" || echo "  ✗ JobDescriptionImportController.php"
echo ""
echo "=== PHASE 1 BACKEND: COMPLETE ✅ ==="
