<?php

namespace App\Services;

use App\Models\EnterpriseSubscription;
use App\Models\Site;
use App\Models\SubscriptionAlert;
use App\Notifications\Subscription\TrialExpiringNotification;
use App\Notifications\Subscription\TrialExpiredNotification;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class TrialService
{
    public const TRIAL_DAYS = 90;

    public function createTrialSubscription(
        Site $site,
        array $offerIds,
        string $paymentGateway,
        string $paymentCustomerId,
        string $paymentMethodId
    ): EnterpriseSubscription {
        return DB::transaction(function () use ($site, $offerIds, $paymentGateway, $paymentCustomerId, $paymentMethodId) {
            // Get first offer (main subscription)
            $mainOfferId = $offerIds[0];
            
            $subscription = EnterpriseSubscription::create([
                'site_id' => $site->id,
                'offer_id' => $mainOfferId,
                'start_date' => now(),
                'expiration_date' => now()->addDays(self::TRIAL_DAYS),
                'is_trial' => true,
                'trial_ends_at' => now()->addDays(self::TRIAL_DAYS),
                'status' => 'trial',
                'payment_status' => 'pending',
                'is_active' => true,
                'payment_gateway' => $paymentGateway,
                'payment_customer_id' => $paymentCustomerId,
                'payment_method_id' => $paymentMethodId,
            ]);

            return $subscription;
        });
    }

    public function scheduleExpirationNotifications(EnterpriseSubscription $subscription): void
    {
        // Alerts are generated by trial:check command based on remaining days.
        // This method is kept for backward compatibility and intentionally left as no-op.
        return;
    }

    public function expireTrials(): int
    {
        $expiredCount = 0;

        $expiredTrials = EnterpriseSubscription::where('is_trial', true)
            ->where('status', 'trial')
            ->where('trial_ends_at', '<=', now())
            ->get();

        foreach ($expiredTrials as $subscription) {
            $subscription->update([
                'status' => 'expired',
                'is_active' => false,
            ]);

            // Notify user
            $user = $subscription->site->enterprise->users()->first();
            if ($user) {
                $user->notify(new TrialExpiredNotification($subscription));
            }

            $expiredCount++;
        }

        return $expiredCount;
    }

    public function sendReminders(): int
    {
        $sentCount = 0;

        $subscriptions = EnterpriseSubscription::where('is_trial', true)
            ->where('status', 'trial')
            ->whereNotNull('trial_ends_at')
            ->get();

        foreach ($subscriptions as $subscription) {
            $daysRemaining = $subscription->daysRemaining();
            $alertType = match ($daysRemaining) {
                30 => 'trial_30',
                15 => 'trial_15',
                7 => 'trial_7',
                3 => 'trial_3',
                1 => 'trial_1',
                default => null,
            };

            if (!$alertType) {
                continue;
            }

            $alreadySent = SubscriptionAlert::where('subscription_id', $subscription->id)
                ->where('alert_type', $alertType)
                ->exists();

            if ($alreadySent) {
                continue;
            }

            $user = $subscription->site->enterprise->users()->first();
            if ($user) {
                $user->notify(new TrialExpiringNotification($subscription, $daysRemaining));
                SubscriptionAlert::create([
                    'subscription_id' => $subscription->id,
                    'alert_type' => $alertType,
                    'sent_at' => now(),
                ]);
                $sentCount++;
            }
        }

        return $sentCount;
    }
}
