export const PERMISSION_LABELS: Record<string, string> = {
  'sites.read': 'Consulter : Sites',
  'sites.create': 'Créer : Sites',
  'sites.update': 'Modifier : Sites',
  'sites.delete': 'Supprimer : Sites',
  'sites.manage': 'Gérer : Sites',
  'verify_documents': 'Vérifier les documents',
  'approve_documents': 'Approuver les documents',
  'contexte.comprehension_organisme.read': 'Consulter : Compréhension de l\'organisme',
  'contexte.comprehension_organisme.update': 'Modifier : Compréhension de l\'organisme',
  'contexte.comprehension_organisme.export': 'Exporter : Compréhension de l\'organisme',
  'contexte.parties_interessees.read': 'Consulter : Parties intéressées',
  'contexte.parties_interessees.create': 'Créer : Parties intéressées',
  'contexte.parties_interessees.update': 'Modifier : Parties intéressées',
  'contexte.parties_interessees.delete': 'Supprimer : Parties intéressées',
  'contexte.parties_interessees.export': 'Exporter : Parties intéressées',
  'contexte.domaine_application.read': 'Consulter : Domaine d\'application',
  'contexte.domaine_application.update': 'Modifier : Domaine d\'application',
  'contexte.domaine_application.export': 'Exporter : Domaine d\'application',
  'contexte.systeme_management.read': 'Consulter : Système de management',
  'contexte.systeme_management.create': 'Créer : Système de management',
  'contexte.systeme_management.update': 'Modifier : Système de management',
  'contexte.systeme_management.delete': 'Supprimer : Système de management',
  'contexte.systeme_management.export': 'Exporter : Système de management',
  'contexte.systeme_management.manage_indicators': 'Gérer les indicateurs',
  'contexte.systeme_management.manage_risks': 'Gérer les risques',
  'leadership.politique.read': 'Consulter : Politique',
  'leadership.politique.create': 'Créer : Politique',
  'leadership.politique.update': 'Modifier : Politique',
  'leadership.politique.delete': 'Supprimer : Politique',
  'leadership.politique.validate': 'Valider : Politique',
  'leadership.politique.export': 'Exporter : Politique',
  'leadership.roles_responsabilites.organigramme.read': 'Consulter l\'organigramme',
  'leadership.roles_responsabilites.organigramme.create': 'Créer l\'organigramme',
  'leadership.roles_responsabilites.organigramme.update': 'Modifier l\'organigramme',
  'leadership.roles_responsabilites.organigramme.delete': 'Supprimer l\'organigramme',
  'leadership.roles_responsabilites.personnel.read': 'Consulter : Personnel',
  'leadership.roles_responsabilites.personnel.create': 'Créer : Personnel',
  'leadership.roles_responsabilites.personnel.update': 'Modifier : Personnel',
  'leadership.roles_responsabilites.personnel.delete': 'Supprimer : Personnel',
  'leadership.roles_responsabilites.personnel.manage_permissions': 'Gérer les permissions',
  'leadership.roles_responsabilites.personnel.export': 'Exporter : Personnel',
  'leadership.roles_responsabilites.fiche_poste.read': 'Consulter : Fiche de poste',
  'leadership.roles_responsabilites.fiche_poste.create': 'Créer : Fiche de poste',
  'leadership.roles_responsabilites.fiche_poste.update': 'Modifier : Fiche de poste',
  'leadership.roles_responsabilites.fiche_poste.delete': 'Supprimer : Fiche de poste',
  'leadership.roles_responsabilites.fiche_poste.export': 'Exporter : Fiche de poste',
  'leadership.roles_responsabilites.fiche_responsabilite.read': 'Consulter : Fiche de responsabilité',
  'leadership.roles_responsabilites.fiche_responsabilite.create': 'Créer : Fiche de responsabilité',
  'leadership.roles_responsabilites.fiche_responsabilite.update': 'Modifier : Fiche de responsabilité',
  'leadership.roles_responsabilites.fiche_responsabilite.delete': 'Supprimer : Fiche de responsabilité',
  'leadership.roles_responsabilites.fiche_responsabilite.export': 'Exporter : Fiche de responsabilité',
  'planification.risques_opportunites.read': 'Consulter : Risques et opportunités',
  'planification.risques_opportunites.create': 'Créer : Risques et opportunités',
  'planification.risques_opportunites.update': 'Modifier : Risques et opportunités',
  'planification.risques_opportunites.delete': 'Supprimer : Risques et opportunités',
  'planification.risques_opportunites.evaluate': 'Évaluer : Risques et opportunités',
  'planification.risques_opportunites.export': 'Exporter : Risques et opportunités',
  'planification.objectifs.read': 'Consulter l\'objectifs',
  'planification.objectifs.create': 'Créer l\'objectifs',
  'planification.objectifs.update': 'Modifier l\'objectifs',
  'planification.objectifs.delete': 'Supprimer l\'objectifs',
  'planification.objectifs.manage_actions': 'Gérer les actions',
  'planification.objectifs.update_tracking': 'Mettre à jour le suivi (Objectifs)',
  'planification.objectifs.export': 'Exporter l\'objectifs',
  'planification.plans_sm.read': 'Consulter : Plans SM',
  'planification.plans_sm.create': 'Créer : Plans SM',
  'planification.plans_sm.update': 'Modifier : Plans SM',
  'planification.plans_sm.delete': 'Supprimer : Plans SM',
  'planification.plans_sm.update_tracking': 'Mettre à jour le suivi (Plans SM)',
  'planification.plans_sm.archive': 'Archiver : Plans SM',
  'planification.plans_sm.export': 'Exporter : Plans SM',
  'support.ressources.read': 'Consulter : Ressources',
  'support.ressources.create': 'Créer : Ressources',
  'support.ressources.update': 'Modifier : Ressources',
  'support.ressources.delete': 'Supprimer : Ressources',
  'support.ressources.transfer': 'Transférer',
  'support.ressources.manage_maintenance': 'Gérer la maintenance',
  'support.ressources.manage_calibration': 'Gérer l\'étalonnage',
  'support.ressources.export': 'Exporter : Ressources',
  'support.competences.read': 'Consulter : Compétences',
  'support.competences.create': 'Créer : Compétences',
  'support.competences.update': 'Modifier : Compétences',
  'support.competences.delete': 'Supprimer : Compétences',
  'support.competences.manage_participants': 'Gérer les participants',
  'support.competences.update_tracking': 'Mettre à jour le suivi (Compétences)',
  'support.competences.export': 'Exporter : Compétences',
  'support.sensibilisation.read': 'Consulter : Sensibilisation',
  'support.sensibilisation.create': 'Créer : Sensibilisation',
  'support.sensibilisation.update': 'Modifier : Sensibilisation',
  'support.sensibilisation.delete': 'Supprimer : Sensibilisation',
  'support.sensibilisation.update_tracking': 'Mettre à jour le suivi (Sensibilisation)',
  'support.communication.read': 'Consulter : Communication',
  'support.communication.create': 'Créer : Communication',
  'support.communication.update': 'Modifier : Communication',
  'support.communication.delete': 'Supprimer : Communication',
  'support.communication.update_tracking': 'Mettre à jour le suivi (Communication)',
  'support.communication.export': 'Exporter : Communication',
  'support.documents.read': 'Consulter : Documents',
  'support.documents.create': 'Créer : Documents',
  'support.documents.update': 'Modifier : Documents',
  'support.documents.delete': 'Supprimer : Documents',
  'support.documents.download': 'Télécharger : Documents',
  'support.documents.import': 'Importer : Documents',
  'support.documents.export': 'Exporter : Documents',
  'support.documents.configure_nomenclature': 'Configurer la nomenclature',
  'support.documents.manage_types': 'Gérer les types',
  'realisation.planification_operationnelle.read': 'Consulter : Planification opérationnelle',
  'realisation.planification_operationnelle.create': 'Créer : Planification opérationnelle',
  'realisation.planification_operationnelle.update': 'Modifier : Planification opérationnelle',
  'realisation.planification_operationnelle.delete': 'Supprimer : Planification opérationnelle',
  'realisation.planification_operationnelle.update_tracking': 'Mettre à jour le suivi (Planification opérationnelle)',
  'realisation.planification_operationnelle.export': 'Exporter : Planification opérationnelle',
  'realisation.obligations_conformite.read': 'Consulter l\'obligations de conformité',
  'realisation.obligations_conformite.create': 'Créer l\'obligations de conformité',
  'realisation.obligations_conformite.update': 'Modifier l\'obligations de conformité',
  'realisation.obligations_conformite.delete': 'Supprimer l\'obligations de conformité',
  'realisation.obligations_conformite.export': 'Exporter l\'obligations de conformité',
  'realisation.conception_developpement.read': 'Consulter : Conception et développement',
  'realisation.conception_developpement.create': 'Créer : Conception et développement',
  'realisation.conception_developpement.update': 'Modifier : Conception et développement',
  'realisation.conception_developpement.delete': 'Supprimer : Conception et développement',
  'realisation.conception_developpement.export': 'Exporter : Conception et développement',
  'realisation.prestataires.read': 'Consulter : Prestataires',
  'realisation.prestataires.create': 'Créer : Prestataires',
  'realisation.prestataires.update': 'Modifier : Prestataires',
  'realisation.prestataires.delete': 'Supprimer : Prestataires',
  'realisation.prestataires.evaluate': 'Évaluer : Prestataires',
  'realisation.prestataires.manage_documents': 'Gérer les documents',
  'realisation.prestataires.export': 'Exporter : Prestataires',
  'realisation.production.read': 'Consulter : Production',
  'realisation.production.create': 'Créer : Production',
  'realisation.production.update': 'Modifier : Production',
  'realisation.production.delete': 'Supprimer : Production',
  'realisation.liberation.read': 'Consulter : Libération',
  'realisation.liberation.create': 'Créer : Libération',
  'realisation.liberation.update': 'Modifier : Libération',
  'realisation.liberation.delete': 'Supprimer : Libération',
  'realisation.liberation.validate': 'Valider : Libération',
  'realisation.sorties_non_conformes.read': 'Consulter : Sorties non conformes',
  'realisation.sorties_non_conformes.create': 'Créer : Sorties non conformes',
  'realisation.sorties_non_conformes.update': 'Modifier : Sorties non conformes',
  'realisation.sorties_non_conformes.delete': 'Supprimer : Sorties non conformes',
  'realisation.sorties_non_conformes.manage_actions': 'Gérer les actions',
  'realisation.sorties_non_conformes.update_tracking': 'Mettre à jour le suivi (Sorties non conformes)',
  'realisation.sorties_non_conformes.manage_complaints': 'Gérer les plaintes',
  'evaluation.pip.read': 'Consulter : PIP',
  'evaluation.pip.create': 'Créer : PIP',
  'evaluation.pip.update': 'Modifier : PIP',
  'evaluation.pip.delete': 'Supprimer : PIP',
  'evaluation.pip.define_criteria': 'Définir les critères',
  'evaluation.pip.generate_link': 'Générer le lien',
  'evaluation.pip.view_submissions': 'Voir les soumissions',
  'evaluation.pip.export': 'Exporter : PIP',
  'evaluation.revue_processus.read': 'Consulter : Revue de processus',
  'evaluation.revue_processus.create': 'Créer : Revue de processus',
  'evaluation.revue_processus.update': 'Modifier : Revue de processus',
  'evaluation.revue_processus.validate': 'Valider : Revue de processus',
  'evaluation.audits.read': 'Consulter l\'audits',
  'evaluation.audits.create': 'Créer l\'audits',
  'evaluation.audits.update': 'Modifier l\'audits',
  'evaluation.audits.delete': 'Supprimer l\'audits',
  'evaluation.audits.add_findings': 'Ajouter des constats',
  'evaluation.audits.evaluate_auditors': 'Évaluer les auditeurs',
  'evaluation.audits.generate_report': 'Générer le rapport',
  'evaluation.audits.export': 'Exporter l\'audits',
  'evaluation.revue_direction.read': 'Consulter : Revue de direction',
  'evaluation.revue_direction.create': 'Créer : Revue de direction',
  'evaluation.revue_direction.update': 'Modifier : Revue de direction',
  'evaluation.revue_direction.delete': 'Supprimer : Revue de direction',
  'evaluation.revue_direction.validate': 'Valider : Revue de direction',
  'evaluation.revue_direction.export': 'Exporter : Revue de direction',
  'amelioration.non_conformites.read': 'Consulter : Non-conformités',
  'amelioration.non_conformites.create': 'Créer : Non-conformités',
  'amelioration.non_conformites.update': 'Modifier : Non-conformités',
  'amelioration.non_conformites.delete': 'Supprimer : Non-conformités',
  'amelioration.non_conformites.analyze_causes': 'Analyser les causes',
  'amelioration.non_conformites.manage_actions': 'Gérer les actions',
  'amelioration.non_conformites.validate_closure': 'Valider la clôture',
  'amelioration.non_conformites.update_tracking': 'Mettre à jour le suivi (Non-conformités)',
  'amelioration.non_conformites.export': 'Exporter : Non-conformités',
  'amelioration.amelioration_continue.read': 'Consulter l\'amélioration continue',
  'amelioration.amelioration_continue.create': 'Créer l\'amélioration continue',
  'amelioration.amelioration_continue.update': 'Modifier l\'amélioration continue',
  'amelioration.amelioration_continue.delete': 'Supprimer l\'amélioration continue',
  'amelioration.amelioration_continue.validate': 'Valider l\'amélioration continue',
  'sst.consultation_participation.read': 'Consulter : Consultation et participation',
  'sst.consultation_participation.create': 'Créer : Consultation et participation',
  'sst.consultation_participation.update': 'Modifier : Consultation et participation',
  'sst.consultation_participation.delete': 'Supprimer : Consultation et participation',
  'sst.duerp.read': 'Consulter : DUERP',
  'sst.duerp.create': 'Créer : DUERP',
  'sst.duerp.update': 'Modifier : DUERP',
  'sst.duerp.delete': 'Supprimer : DUERP',
  'sst.duerp.export': 'Exporter : DUERP',
  'sst.identification_dangers.read': 'Consulter l\'identification des dangers',
  'sst.identification_dangers.create': 'Créer l\'identification des dangers',
  'sst.identification_dangers.update': 'Modifier l\'identification des dangers',
  'sst.identification_dangers.delete': 'Supprimer l\'identification des dangers',
  'sst.identification_dangers.evaluate': 'Évaluer l\'identification des dangers',
  'sst.exigences_legales.read': 'Consulter l\'exigences légales',
  'sst.exigences_legales.create': 'Créer l\'exigences légales',
  'sst.exigences_legales.update': 'Modifier l\'exigences légales',
  'sst.exigences_legales.delete': 'Supprimer l\'exigences légales',
  'sst.habilitations.read': 'Consulter : Habilitations',
  'sst.habilitations.create': 'Créer : Habilitations',
  'sst.habilitations.update': 'Modifier : Habilitations',
  'sst.habilitations.delete': 'Supprimer : Habilitations',
  'sst.habilitations.manage_alerts': 'Gérer les alertes',
  'sst.epi.read': 'Consulter l\'epi',
  'sst.epi.manage_stock': 'Gérer le stock',
  'sst.epi.assign': 'Assigner l\'epi',
  'sst.epi.view_movements': 'Voir les mouvements',
  'sst.vgp.read': 'Consulter : VGP',
  'sst.vgp.create': 'Créer : VGP',
  'sst.vgp.update': 'Modifier : VGP',
  'sst.vgp.delete': 'Supprimer : VGP',
  'sst.vgp.validate': 'Valider : VGP',
  'environnement.aspects.read': 'Consulter l\'aspects environnementaux',
  'environnement.aspects.create': 'Créer l\'aspects environnementaux',
  'environnement.aspects.update': 'Modifier l\'aspects environnementaux',
  'environnement.aspects.delete': 'Supprimer l\'aspects environnementaux',
  'environnement.aspects.evaluate': 'Évaluer l\'aspects environnementaux',
  'environnement.revue_environnementale.read': 'Consulter : Revue environnementale',
  'environnement.revue_environnementale.create': 'Créer : Revue environnementale',
  'environnement.revue_environnementale.update': 'Modifier : Revue environnementale',
  'environnement.maitrise_operationnelle.read': 'Consulter : Maîtrise opérationnelle',
  'environnement.maitrise_operationnelle.create': 'Créer : Maîtrise opérationnelle',
  'environnement.maitrise_operationnelle.update': 'Modifier : Maîtrise opérationnelle',
  'environnement.maitrise_operationnelle.delete': 'Supprimer : Maîtrise opérationnelle',
  'environnement.urgences.read': 'Consulter : Urgences',
  'environnement.urgences.create': 'Créer : Urgences',
  'environnement.urgences.update': 'Modifier : Urgences',
  'environnement.urgences.delete': 'Supprimer : Urgences',
  'energie.revue_energetique.read': 'Consulter : Revue énergétique',
  'energie.revue_energetique.create': 'Créer : Revue énergétique',
  'energie.revue_energetique.update': 'Modifier : Revue énergétique',
  'energie.ipe.read': 'Consulter l\'ipe',
  'energie.ipe.create': 'Créer l\'ipe',
  'energie.ipe.update': 'Modifier l\'ipe',
  'energie.ipe.delete': 'Supprimer l\'ipe',
  'energie.ipe.calculate': 'Calculer',
  'energie.consommations.read': 'Consulter : Consommations',
  'energie.consommations.create': 'Créer : Consommations',
  'energie.consommations.update': 'Modifier : Consommations',
  'energie.consommations.delete': 'Supprimer : Consommations',
  'energie.consommations.import': 'Importer : Consommations',
  'energie.objectifs_energetiques.read': 'Consulter l\'objectifs énergétiques',
  'energie.objectifs_energetiques.create': 'Créer l\'objectifs énergétiques',
  'energie.objectifs_energetiques.update': 'Modifier l\'objectifs énergétiques',
  'energie.objectifs_energetiques.delete': 'Supprimer l\'objectifs énergétiques',
  'si.evaluation_risques.read': 'Consulter l\'évaluation des risques si',
  'si.evaluation_risques.create': 'Créer l\'évaluation des risques si',
  'si.evaluation_risques.update': 'Modifier l\'évaluation des risques si',
  'si.evaluation_risques.delete': 'Supprimer l\'évaluation des risques si',
  'si.evaluation_risques.evaluate': 'Évaluer l\'évaluation des risques si',
  'si.declaration_applicabilite.read': 'Consulter : Déclaration d\'applicabilité',
  'si.declaration_applicabilite.create': 'Créer : Déclaration d\'applicabilité',
  'si.declaration_applicabilite.update': 'Modifier : Déclaration d\'applicabilité',
  'si.inventaire_actifs.read': 'Consulter l\'inventaire des actifs',
  'si.inventaire_actifs.create': 'Créer l\'inventaire des actifs',
  'si.inventaire_actifs.update': 'Modifier l\'inventaire des actifs',
  'si.inventaire_actifs.delete': 'Supprimer l\'inventaire des actifs',
  'si.controles_acces.read': 'Consulter : Contrôles d\'accès',
  'si.controles_acces.create': 'Créer : Contrôles d\'accès',
  'si.controles_acces.update': 'Modifier : Contrôles d\'accès',
  'si.controles_acces.delete': 'Supprimer : Contrôles d\'accès',
  'si.incidents_si.read': 'Consulter l\'incidents si',
  'si.incidents_si.create': 'Créer l\'incidents si',
  'si.incidents_si.update': 'Modifier l\'incidents si',
  'si.incidents_si.close': 'Clôturer',
  'alimentaire.analyse_dangers.read': 'Consulter l\'analyse des dangers',
  'alimentaire.analyse_dangers.create': 'Créer l\'analyse des dangers',
  'alimentaire.analyse_dangers.update': 'Modifier l\'analyse des dangers',
  'alimentaire.analyse_dangers.delete': 'Supprimer l\'analyse des dangers',
  'alimentaire.ccp.read': 'Consulter : CCP',
  'alimentaire.ccp.create': 'Créer : CCP',
  'alimentaire.ccp.update': 'Modifier : CCP',
  'alimentaire.ccp.delete': 'Supprimer : CCP',
  'alimentaire.ccp.monitor': 'Surveiller',
  'alimentaire.plan_haccp.read': 'Consulter : Plan HACCP',
  'alimentaire.plan_haccp.create': 'Créer : Plan HACCP',
  'alimentaire.plan_haccp.update': 'Modifier : Plan HACCP',
  'alimentaire.plan_haccp.validate': 'Valider : Plan HACCP',
  'alimentaire.tracabilite.read': 'Consulter : Traçabilité',
  'alimentaire.tracabilite.create': 'Créer : Traçabilité',
  'alimentaire.tracabilite.update': 'Modifier : Traçabilité',
  'alimentaire.tracabilite.delete': 'Supprimer : Traçabilité',
  'roles.read': 'Consulter : Rôles',
  'roles.create': 'Créer : Rôles',
  'roles.update': 'Modifier : Rôles',
  'roles.delete': 'Supprimer : Rôles',
  'roles.assign': 'Assigner : Rôles',
  'roles.copy_to_site': 'Copier vers un site',
  'permissions.manage': 'Gérer : Permissions',
  'dashboard.read': 'Consulter : Tableau de bord',
  'settings.read': 'Consulter : Paramètres',
  'settings.update': 'Modifier : Paramètres',
  'security_audit.read': 'Consulter l\'audit de sécurité',
  'subscriptions.read': 'Consulter : Souscriptions',
  'subscriptions.create': 'Créer : Souscriptions',
  'subscriptions.update': 'Modifier : Souscriptions',
  'subscriptions.renew': 'Renouveler',
  'subscriptions.cancel': 'Annuler',
  'users.read': 'Consulter : Utilisateurs',
  'users.create': 'Créer : Utilisateurs',
  'users.update': 'Modifier : Utilisateurs',
  'users.delete': 'Supprimer : Utilisateurs',
  'users.manage': 'Gérer : Utilisateurs',
  'norm_library.read': 'Consulter : Bibliothèque de normes',
}

export function mapPermissionLabel(name: string): string {
  if (!name) return ''
  if (PERMISSION_LABELS[name]) return PERMISSION_LABELS[name]

  const parts = name.split('.')
  const action = parts.pop() || name
  const resource = parts.join('.')

  const actionMap: Record<string, string> = {
    read: 'Consulter',
    create: 'Créer',
    update: 'Modifier',
    delete: 'Supprimer',
    import: 'Importer',
    export: 'Exporter',
    verify: 'Vérifier',
    approve: 'Approuver',
    view_all: 'Voir toutes',
    manage_holidays: 'Gérer jours fériés'
  }

  const actionLabel = actionMap[action] || (action.charAt(0).toUpperCase() + action.slice(1))
  if (resource) {
    const human = resource.replace(/[\_\-]/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
    return `${actionLabel} : ${human}`
  }
  return actionLabel
}
