<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkflowStateSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        
        $states = [
            // ===== NON-CONFORMITÉS =====
            [
                'entity_type' => 'NonConformity',
                'code' => 'draft',
                'label' => 'Brouillon',
                'color' => '#9CA3AF',
                'description' => 'NC en cours de rédaction',
                'order' => 1,
                'is_initial' => true,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_analysis']),
                'required_fields' => json_encode(['description', 'severity']),
                'permissions' => json_encode(['create_nc']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'NonConformity',
                'code' => 'in_analysis',
                'label' => 'En analyse',
                'color' => '#F59E0B',
                'description' => 'Analyse des causes en cours',
                'order' => 2,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['validated', 'draft']),
                'required_fields' => json_encode(['cause_analysis', 'corrective_action']),
                'permissions' => json_encode(['analyze_nc']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'NonConformity',
                'code' => 'validated',
                'label' => 'Validée',
                'color' => '#3B82F6',
                'description' => 'NC validée, actions en cours',
                'order' => 3,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_verification']),
                'required_fields' => json_encode(['responsible_id', 'deadline']),
                'permissions' => json_encode(['validate_nc']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'NonConformity',
                'code' => 'in_verification',
                'label' => 'En vérification',
                'color' => '#8B5CF6',
                'description' => 'Vérification de l\'efficacité',
                'order' => 4,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['closed', 'validated']),
                'required_fields' => json_encode(['effectiveness_verified']),
                'permissions' => json_encode(['verify_nc']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'NonConformity',
                'code' => 'closed',
                'label' => 'Clôturée',
                'color' => '#10B981',
                'description' => 'NC clôturée',
                'order' => 5,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode(['resolution_date', 'verification_date']),
                'permissions' => json_encode(['close_nc']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== AUDITS =====
            [
                'entity_type' => 'Audit',
                'code' => 'planned',
                'label' => 'Planifié',
                'color' => '#9CA3AF',
                'description' => 'Audit planifié',
                'order' => 1,
                'is_initial' => true,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_progress', 'cancelled']),
                'required_fields' => json_encode(['planned_date', 'lead_auditor_id']),
                'permissions' => json_encode(['plan_audit']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Audit',
                'code' => 'in_progress',
                'label' => 'En cours',
                'color' => '#3B82F6',
                'description' => 'Audit en cours de réalisation',
                'order' => 2,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_reporting']),
                'required_fields' => json_encode(['actual_date']),
                'permissions' => json_encode(['conduct_audit']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Audit',
                'code' => 'in_reporting',
                'label' => 'En rapport',
                'color' => '#F59E0B',
                'description' => 'Rédaction du rapport',
                'order' => 3,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['completed']),
                'required_fields' => json_encode(['findings', 'conclusion']),
                'permissions' => json_encode(['report_audit']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Audit',
                'code' => 'completed',
                'label' => 'Terminé',
                'color' => '#10B981',
                'description' => 'Audit terminé',
                'order' => 4,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode(['report_path']),
                'permissions' => json_encode(['close_audit']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Audit',
                'code' => 'cancelled',
                'label' => 'Annulé',
                'color' => '#EF4444',
                'description' => 'Audit annulé',
                'order' => 5,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode([]),
                'permissions' => json_encode(['cancel_audit']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== ACTIONS =====
            [
                'entity_type' => 'Action',
                'code' => 'draft',
                'label' => 'Brouillon',
                'color' => '#9CA3AF',
                'description' => 'Action en cours de définition',
                'order' => 1,
                'is_initial' => true,
                'is_final' => false,
                'allowed_transitions' => json_encode(['planned']),
                'required_fields' => json_encode(['title', 'description']),
                'permissions' => json_encode(['create_action']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Action',
                'code' => 'planned',
                'label' => 'Planifiée',
                'color' => '#3B82F6',
                'description' => 'Action planifiée',
                'order' => 2,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_progress', 'cancelled']),
                'required_fields' => json_encode(['responsible_id', 'deadline']),
                'permissions' => json_encode(['plan_action']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Action',
                'code' => 'in_progress',
                'label' => 'En cours',
                'color' => '#F59E0B',
                'description' => 'Action en cours de réalisation',
                'order' => 3,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_verification', 'delayed']),
                'required_fields' => json_encode(['progress']),
                'permissions' => json_encode(['execute_action']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Action',
                'code' => 'delayed',
                'label' => 'En retard',
                'color' => '#DC2626',
                'description' => 'Action en retard',
                'order' => 4,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_progress', 'cancelled']),
                'required_fields' => json_encode([]),
                'permissions' => json_encode(['manage_action']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Action',
                'code' => 'in_verification',
                'label' => 'En vérification',
                'color' => '#8B5CF6',
                'description' => 'Vérification de l\'efficacité',
                'order' => 5,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['completed', 'in_progress']),
                'required_fields' => json_encode(['effectiveness_verified']),
                'permissions' => json_encode(['verify_action']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Action',
                'code' => 'completed',
                'label' => 'Terminée',
                'color' => '#10B981',
                'description' => 'Action terminée et efficace',
                'order' => 6,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode(['verification_date']),
                'permissions' => json_encode(['close_action']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Action',
                'code' => 'cancelled',
                'label' => 'Annulée',
                'color' => '#EF4444',
                'description' => 'Action annulée',
                'order' => 7,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode([]),
                'permissions' => json_encode(['cancel_action']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== OBJECTIFS =====
            [
                'entity_type' => 'Objective',
                'code' => 'draft',
                'label' => 'Brouillon',
                'color' => '#9CA3AF',
                'description' => 'Objectif en définition',
                'order' => 1,
                'is_initial' => true,
                'is_final' => false,
                'allowed_transitions' => json_encode(['active']),
                'required_fields' => json_encode(['title', 'target_value']),
                'permissions' => json_encode(['create_objective']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Objective',
                'code' => 'active',
                'label' => 'En cours',
                'color' => '#3B82F6',
                'description' => 'Objectif actif',
                'order' => 2,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['achieved', 'not_achieved', 'cancelled']),
                'required_fields' => json_encode(['deadline', 'responsible_id']),
                'permissions' => json_encode(['activate_objective']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Objective',
                'code' => 'achieved',
                'label' => 'Atteint',
                'color' => '#10B981',
                'description' => 'Objectif atteint',
                'order' => 3,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode(['current_value']),
                'permissions' => json_encode(['close_objective']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Objective',
                'code' => 'not_achieved',
                'label' => 'Non atteint',
                'color' => '#EF4444',
                'description' => 'Objectif non atteint',
                'order' => 4,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode(['current_value']),
                'permissions' => json_encode(['close_objective']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Objective',
                'code' => 'cancelled',
                'label' => 'Annulé',
                'color' => '#6B7280',
                'description' => 'Objectif annulé',
                'order' => 5,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode([]),
                'permissions' => json_encode(['cancel_objective']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== RISQUES/OPPORTUNITÉS =====
            [
                'entity_type' => 'Risk',
                'code' => 'identified',
                'label' => 'Identifié',
                'color' => '#F59E0B',
                'description' => 'Risque/opportunité identifié',
                'order' => 1,
                'is_initial' => true,
                'is_final' => false,
                'allowed_transitions' => json_encode(['assessed']),
                'required_fields' => json_encode(['description']),
                'permissions' => json_encode(['create_risk']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Risk',
                'code' => 'assessed',
                'label' => 'Évalué',
                'color' => '#3B82F6',
                'description' => 'Cotation effectuée',
                'order' => 2,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_treatment', 'accepted']),
                'required_fields' => json_encode(['probability', 'gravity', 'criticality']),
                'permissions' => json_encode(['assess_risk']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Risk',
                'code' => 'in_treatment',
                'label' => 'En traitement',
                'color' => '#8B5CF6',
                'description' => 'Mesures de maîtrise en cours',
                'order' => 3,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['controlled', 'assessed']),
                'required_fields' => json_encode(['treatment', 'responsible_id']),
                'permissions' => json_encode(['treat_risk']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Risk',
                'code' => 'controlled',
                'label' => 'Maîtrisé',
                'color' => '#10B981',
                'description' => 'Risque maîtrisé',
                'order' => 4,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode(['residual_assessment']),
                'permissions' => json_encode(['close_risk']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Risk',
                'code' => 'accepted',
                'label' => 'Accepté',
                'color' => '#6B7280',
                'description' => 'Risque accepté',
                'order' => 5,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode([]),
                'permissions' => json_encode(['accept_risk']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== RÉCLAMATIONS =====
            [
                'entity_type' => 'Reclamation',
                'code' => 'received',
                'label' => 'Reçue',
                'color' => '#F59E0B',
                'description' => 'Réclamation reçue',
                'order' => 1,
                'is_initial' => true,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_analysis']),
                'required_fields' => json_encode(['description', 'received_date']),
                'permissions' => json_encode(['create_reclamation']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Reclamation',
                'code' => 'in_analysis',
                'label' => 'En analyse',
                'color' => '#3B82F6',
                'description' => 'Analyse en cours',
                'order' => 2,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['in_treatment']),
                'required_fields' => json_encode(['analysis', 'assigned_to']),
                'permissions' => json_encode(['analyze_reclamation']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Reclamation',
                'code' => 'in_treatment',
                'label' => 'En traitement',
                'color' => '#8B5CF6',
                'description' => 'Traitement en cours',
                'order' => 3,
                'is_initial' => false,
                'is_final' => false,
                'allowed_transitions' => json_encode(['closed']),
                'required_fields' => json_encode(['immediate_response']),
                'permissions' => json_encode(['treat_reclamation']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'entity_type' => 'Reclamation',
                'code' => 'closed',
                'label' => 'Clôturée',
                'color' => '#10B981',
                'description' => 'Réclamation clôturée',
                'order' => 4,
                'is_initial' => false,
                'is_final' => true,
                'allowed_transitions' => json_encode([]),
                'required_fields' => json_encode(['response_date', 'closed_date']),
                'permissions' => json_encode(['close_reclamation']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($states as $state) {
            $payload = $state;
            unset($payload['created_at']);

            DB::table('workflow_states')->updateOrInsert(
                [
                    'entity_type' => $state['entity_type'],
                    'code' => $state['code'],
                ],
                $payload,
            );
        }
    }
}
