/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/auth/components/email-verification/EmailVerificationActions': RouteRecordInfo<'/auth/components/email-verification/EmailVerificationActions', '/auth/components/email-verification/EmailVerificationActions', Record<never, never>, Record<never, never>>,
    '/auth/components/email-verification/EmailVerificationHeader': RouteRecordInfo<'/auth/components/email-verification/EmailVerificationHeader', '/auth/components/email-verification/EmailVerificationHeader', Record<never, never>, Record<never, never>>,
    '/auth/components/email-verification-result/EmailVerificationFailedCard': RouteRecordInfo<'/auth/components/email-verification-result/EmailVerificationFailedCard', '/auth/components/email-verification-result/EmailVerificationFailedCard', Record<never, never>, Record<never, never>>,
    '/auth/components/email-verification-result/EmailVerificationFailedHeader': RouteRecordInfo<'/auth/components/email-verification-result/EmailVerificationFailedHeader', '/auth/components/email-verification-result/EmailVerificationFailedHeader', Record<never, never>, Record<never, never>>,
    '/auth/components/email-verification-result/EmailVerificationSuccessCard': RouteRecordInfo<'/auth/components/email-verification-result/EmailVerificationSuccessCard', '/auth/components/email-verification-result/EmailVerificationSuccessCard', Record<never, never>, Record<never, never>>,
    '/auth/components/email-verification-result/EmailVerificationSuccessHeader': RouteRecordInfo<'/auth/components/email-verification-result/EmailVerificationSuccessHeader', '/auth/components/email-verification-result/EmailVerificationSuccessHeader', Record<never, never>, Record<never, never>>,
    '/auth/components/email-verification-result/EmailVerificationTipCard': RouteRecordInfo<'/auth/components/email-verification-result/EmailVerificationTipCard', '/auth/components/email-verification-result/EmailVerificationTipCard', Record<never, never>, Record<never, never>>,
    '/auth/components/forgot-password/ForgotPasswordForm': RouteRecordInfo<'/auth/components/forgot-password/ForgotPasswordForm', '/auth/components/forgot-password/ForgotPasswordForm', Record<never, never>, Record<never, never>>,
    '/auth/components/forgot-password/ForgotPasswordSuccess': RouteRecordInfo<'/auth/components/forgot-password/ForgotPasswordSuccess', '/auth/components/forgot-password/ForgotPasswordSuccess', Record<never, never>, Record<never, never>>,
    '/auth/components/LoginBrandingPanel': RouteRecordInfo<'/auth/components/LoginBrandingPanel', '/auth/components/LoginBrandingPanel', Record<never, never>, Record<never, never>>,
    '/auth/components/LoginDemoAccounts': RouteRecordInfo<'/auth/components/LoginDemoAccounts', '/auth/components/LoginDemoAccounts', Record<never, never>, Record<never, never>>,
    '/auth/components/reset-password/ResetPasswordBrand': RouteRecordInfo<'/auth/components/reset-password/ResetPasswordBrand', '/auth/components/reset-password/ResetPasswordBrand', Record<never, never>, Record<never, never>>,
    '/auth/components/reset-password/ResetPasswordVisual': RouteRecordInfo<'/auth/components/reset-password/ResetPasswordVisual', '/auth/components/reset-password/ResetPasswordVisual', Record<never, never>, Record<never, never>>,
    '/auth/components/signup-clientb/SignupHeader': RouteRecordInfo<'/auth/components/signup-clientb/SignupHeader', '/auth/components/signup-clientb/SignupHeader', Record<never, never>, Record<never, never>>,
    '/auth/components/signup-clientb/SignupHelpCard': RouteRecordInfo<'/auth/components/signup-clientb/SignupHelpCard', '/auth/components/signup-clientb/SignupHelpCard', Record<never, never>, Record<never, never>>,
    '/auth/components/signup-clientb/SignupTerms': RouteRecordInfo<'/auth/components/signup-clientb/SignupTerms', '/auth/components/signup-clientb/SignupTerms', Record<never, never>, Record<never, never>>,
    '/auth/components/signup-status/PendingApprovalCard': RouteRecordInfo<'/auth/components/signup-status/PendingApprovalCard', '/auth/components/signup-status/PendingApprovalCard', Record<never, never>, Record<never, never>>,
    '/auth/components/signup-status/SignupLoadingCard': RouteRecordInfo<'/auth/components/signup-status/SignupLoadingCard', '/auth/components/signup-status/SignupLoadingCard', Record<never, never>, Record<never, never>>,
    '/auth/components/signup-status/SignupSuccessCard': RouteRecordInfo<'/auth/components/signup-status/SignupSuccessCard', '/auth/components/signup-status/SignupSuccessCard', Record<never, never>, Record<never, never>>,
    '/auth/components/signup-status/SignupSuccessHeader': RouteRecordInfo<'/auth/components/signup-status/SignupSuccessHeader', '/auth/components/signup-status/SignupSuccessHeader', Record<never, never>, Record<never, never>>,
    '/auth/components/SignupCompanyHeader': RouteRecordInfo<'/auth/components/SignupCompanyHeader', '/auth/components/SignupCompanyHeader', Record<never, never>, Record<never, never>>,
    '/auth/components/SignupCompanyTerms': RouteRecordInfo<'/auth/components/SignupCompanyTerms', '/auth/components/SignupCompanyTerms', Record<never, never>, Record<never, never>>,
    '/auth/components/SignupLandingHeader': RouteRecordInfo<'/auth/components/SignupLandingHeader', '/auth/components/SignupLandingHeader', Record<never, never>, Record<never, never>>,
    '/auth/components/SignupLoginLink': RouteRecordInfo<'/auth/components/SignupLoginLink', '/auth/components/SignupLoginLink', Record<never, never>, Record<never, never>>,
    '/auth/email-verification-failed': RouteRecordInfo<'/auth/email-verification-failed', '/auth/email-verification-failed', Record<never, never>, Record<never, never>>,
    '/auth/email-verified': RouteRecordInfo<'/auth/email-verified', '/auth/email-verified', Record<never, never>, Record<never, never>>,
    '/auth/EmailVerification': RouteRecordInfo<'/auth/EmailVerification', '/auth/EmailVerification', Record<never, never>, Record<never, never>>,
    '/auth/ForcePasswordChange': RouteRecordInfo<'/auth/ForcePasswordChange', '/auth/ForcePasswordChange', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/ForgotPassword': RouteRecordInfo<'/auth/ForgotPassword', '/auth/ForgotPassword', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/LoginModern': RouteRecordInfo<'/auth/LoginModern', '/auth/LoginModern', Record<never, never>, Record<never, never>>,
    '/auth/ModernLogin': RouteRecordInfo<'/auth/ModernLogin', '/auth/ModernLogin', Record<never, never>, Record<never, never>>,
    '/auth/OAuthCallback': RouteRecordInfo<'/auth/OAuthCallback', '/auth/OAuthCallback', Record<never, never>, Record<never, never>>,
    '/auth/pending-approval': RouteRecordInfo<'/auth/pending-approval', '/auth/pending-approval', Record<never, never>, Record<never, never>>,
    '/auth/reset-password': RouteRecordInfo<'/auth/reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/signup/clientb': RouteRecordInfo<'/auth/signup/clientb', '/auth/signup/clientb', Record<never, never>, Record<never, never>>,
    '/auth/signup/company-old-backup': RouteRecordInfo<'/auth/signup/company-old-backup', '/auth/signup/company-old-backup', Record<never, never>, Record<never, never>>,
    '/auth/signup/CompanySignupModern': RouteRecordInfo<'/auth/signup/CompanySignupModern', '/auth/signup/CompanySignupModern', Record<never, never>, Record<never, never>>,
    '/auth/signup/individual': RouteRecordInfo<'/auth/signup/individual', '/auth/signup/individual', Record<never, never>, Record<never, never>>,
    '/auth/signup/individual-new': RouteRecordInfo<'/auth/signup/individual-new', '/auth/signup/individual-new', Record<never, never>, Record<never, never>>,
    '/auth/Signup': RouteRecordInfo<'/auth/Signup', '/auth/Signup', Record<never, never>, Record<never, never>>,
    '/auth/signup-loading': RouteRecordInfo<'/auth/signup-loading', '/auth/signup-loading', Record<never, never>, Record<never, never>>,
    '/auth/signup-success': RouteRecordInfo<'/auth/signup-success', '/auth/signup-success', Record<never, never>, Record<never, never>>,
    '/auth/SignupClientA': RouteRecordInfo<'/auth/SignupClientA', '/auth/SignupClientA', Record<never, never>, Record<never, never>>,
    '/auth/SignupClientB': RouteRecordInfo<'/auth/SignupClientB', '/auth/SignupClientB', Record<never, never>, Record<never, never>>,
    '/contexts/Form': RouteRecordInfo<'/contexts/Form', '/contexts/Form', Record<never, never>, Record<never, never>>,
    '/contexts/List': RouteRecordInfo<'/contexts/List', '/contexts/List', Record<never, never>, Record<never, never>>,
    '/contexts/View': RouteRecordInfo<'/contexts/View', '/contexts/View', Record<never, never>, Record<never, never>>,
    '/demo-ui': RouteRecordInfo<'/demo-ui', '/demo-ui', Record<never, never>, Record<never, never>>,
    '/documents/': RouteRecordInfo<'/documents/', '/documents', Record<never, never>, Record<never, never>>,
    '/documents/[id]': RouteRecordInfo<'/documents/[id]', '/documents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/documents/CodeApproval': RouteRecordInfo<'/documents/CodeApproval', '/documents/CodeApproval', Record<never, never>, Record<never, never>>,
    '/documents/CodeRecycling': RouteRecordInfo<'/documents/CodeRecycling', '/documents/CodeRecycling', Record<never, never>, Record<never, never>>,
    '/documents/CodeVerification': RouteRecordInfo<'/documents/CodeVerification', '/documents/CodeVerification', Record<never, never>, Record<never, never>>,
    '/documents/DocumentImport': RouteRecordInfo<'/documents/DocumentImport', '/documents/DocumentImport', Record<never, never>, Record<never, never>>,
    '/documents/WorkflowDashboard': RouteRecordInfo<'/documents/WorkflowDashboard', '/documents/WorkflowDashboard', Record<never, never>, Record<never, never>>,
    '/GuideUtilisationPage': RouteRecordInfo<'/GuideUtilisationPage', '/GuideUtilisationPage', Record<never, never>, Record<never, never>>,
    '/improvement/': RouteRecordInfo<'/improvement/', '/improvement', Record<never, never>, Record<never, never>>,
    '/improvement/actions/': RouteRecordInfo<'/improvement/actions/', '/improvement/actions', Record<never, never>, Record<never, never>>,
    '/improvement/actions/[id]': RouteRecordInfo<'/improvement/actions/[id]', '/improvement/actions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/improvement/actions/detail': RouteRecordInfo<'/improvement/actions/detail', '/improvement/actions/detail', Record<never, never>, Record<never, never>>,
    '/improvement/actions/index-new': RouteRecordInfo<'/improvement/actions/index-new', '/improvement/actions/index-new', Record<never, never>, Record<never, never>>,
    '/improvement/audits/': RouteRecordInfo<'/improvement/audits/', '/improvement/audits', Record<never, never>, Record<never, never>>,
    '/improvement/audits/[id]': RouteRecordInfo<'/improvement/audits/[id]', '/improvement/audits/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/improvement/dashboard': RouteRecordInfo<'/improvement/dashboard', '/improvement/dashboard', Record<never, never>, Record<never, never>>,
    '/improvement/kpi/': RouteRecordInfo<'/improvement/kpi/', '/improvement/kpi', Record<never, never>, Record<never, never>>,
    '/improvement/kpi/dashboard': RouteRecordInfo<'/improvement/kpi/dashboard', '/improvement/kpi/dashboard', Record<never, never>, Record<never, never>>,
    '/improvement/non-conformities/': RouteRecordInfo<'/improvement/non-conformities/', '/improvement/non-conformities', Record<never, never>, Record<never, never>>,
    '/improvement/non-conformities/[id]': RouteRecordInfo<'/improvement/non-conformities/[id]', '/improvement/non-conformities/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/improvement/objectives/': RouteRecordInfo<'/improvement/objectives/', '/improvement/objectives', Record<never, never>, Record<never, never>>,
    '/improvement/performance/audits-internes': RouteRecordInfo<'/improvement/performance/audits-internes', '/improvement/performance/audits-internes', Record<never, never>, Record<never, never>>,
    '/improvement/performance/dashboard': RouteRecordInfo<'/improvement/performance/dashboard', '/improvement/performance/dashboard', Record<never, never>, Record<never, never>>,
    '/improvement/performance/revue-direction': RouteRecordInfo<'/improvement/performance/revue-direction', '/improvement/performance/revue-direction', Record<never, never>, Record<never, never>>,
    '/improvement/performance/surveillance': RouteRecordInfo<'/improvement/performance/surveillance', '/improvement/performance/surveillance', Record<never, never>, Record<never, never>>,
    '/improvement/reclamations/': RouteRecordInfo<'/improvement/reclamations/', '/improvement/reclamations', Record<never, never>, Record<never, never>>,
    '/improvement/risks/': RouteRecordInfo<'/improvement/risks/', '/improvement/risks', Record<never, never>, Record<never, never>>,
    '/iso/energie/consommations': RouteRecordInfo<'/iso/energie/consommations', '/iso/energie/consommations', Record<never, never>, Record<never, never>>,
    '/iso/energie/ipe': RouteRecordInfo<'/iso/energie/ipe', '/iso/energie/ipe', Record<never, never>, Record<never, never>>,
    '/iso/environnement/aspects': RouteRecordInfo<'/iso/environnement/aspects', '/iso/environnement/aspects', Record<never, never>, Record<never, never>>,
    '/iso/environnement/obligations': RouteRecordInfo<'/iso/environnement/obligations', '/iso/environnement/obligations', Record<never, never>, Record<never, never>>,
    '/iso/leadership/JobDescriptions': RouteRecordInfo<'/iso/leadership/JobDescriptions', '/iso/leadership/JobDescriptions', Record<never, never>, Record<never, never>>,
    '/iso/leadership/OrgChart': RouteRecordInfo<'/iso/leadership/OrgChart', '/iso/leadership/OrgChart', Record<never, never>, Record<never, never>>,
    '/iso/leadership/Policy': RouteRecordInfo<'/iso/leadership/Policy', '/iso/leadership/Policy', Record<never, never>, Record<never, never>>,
    '/iso/planning/ActionPlans': RouteRecordInfo<'/iso/planning/ActionPlans', '/iso/planning/ActionPlans', Record<never, never>, Record<never, never>>,
    '/iso/planning/components/ActionPlansHero': RouteRecordInfo<'/iso/planning/components/ActionPlansHero', '/iso/planning/components/ActionPlansHero', Record<never, never>, Record<never, never>>,
    '/iso/planning/components/ActionPlansInfoBanner': RouteRecordInfo<'/iso/planning/components/ActionPlansInfoBanner', '/iso/planning/components/ActionPlansInfoBanner', Record<never, never>, Record<never, never>>,
    '/iso/planning/components/ActionPlansMetrics': RouteRecordInfo<'/iso/planning/components/ActionPlansMetrics', '/iso/planning/components/ActionPlansMetrics', Record<never, never>, Record<never, never>>,
    '/iso/planning/components/ActionPlansNote': RouteRecordInfo<'/iso/planning/components/ActionPlansNote', '/iso/planning/components/ActionPlansNote', Record<never, never>, Record<never, never>>,
    '/iso/planning/components/ActionPlansTable': RouteRecordInfo<'/iso/planning/components/ActionPlansTable', '/iso/planning/components/ActionPlansTable', Record<never, never>, Record<never, never>>,
    '/iso/planning/Objectives': RouteRecordInfo<'/iso/planning/Objectives', '/iso/planning/Objectives', Record<never, never>, Record<never, never>>,
    '/iso/planning/RisksOpportunities': RouteRecordInfo<'/iso/planning/RisksOpportunities', '/iso/planning/RisksOpportunities', Record<never, never>, Record<never, never>>,
    '/iso/securite/epi': RouteRecordInfo<'/iso/securite/epi', '/iso/securite/epi', Record<never, never>, Record<never, never>>,
    '/iso/securite/habilitations': RouteRecordInfo<'/iso/securite/habilitations', '/iso/securite/habilitations', Record<never, never>, Record<never, never>>,
    '/iso/securite/vgp': RouteRecordInfo<'/iso/securite/vgp', '/iso/securite/vgp', Record<never, never>, Record<never, never>>,
    '/iso/support/Communication': RouteRecordInfo<'/iso/support/Communication', '/iso/support/Communication', Record<never, never>, Record<never, never>>,
    '/iso/support/Equipment': RouteRecordInfo<'/iso/support/Equipment', '/iso/support/Equipment', Record<never, never>, Record<never, never>>,
    '/kyc/DocumentUpload': RouteRecordInfo<'/kyc/DocumentUpload', '/kyc/DocumentUpload', Record<never, never>, Record<never, never>>,
    '/kyc/Pending': RouteRecordInfo<'/kyc/Pending', '/kyc/Pending', Record<never, never>, Record<never, never>>,
    '/kyc/ValidationPending': RouteRecordInfo<'/kyc/ValidationPending', '/kyc/ValidationPending', Record<never, never>, Record<never, never>>,
    '/landing/components/LandingFooter': RouteRecordInfo<'/landing/components/LandingFooter', '/landing/components/LandingFooter', Record<never, never>, Record<never, never>>,
    '/landing/components/LandingNavbar': RouteRecordInfo<'/landing/components/LandingNavbar', '/landing/components/LandingNavbar', Record<never, never>, Record<never, never>>,
    '/LandingPage': RouteRecordInfo<'/LandingPage', '/LandingPage', Record<never, never>, Record<never, never>>,
    '/LockScreen': RouteRecordInfo<'/LockScreen', '/LockScreen', Record<never, never>, Record<never, never>>,
    '/management-reviews/Form': RouteRecordInfo<'/management-reviews/Form', '/management-reviews/Form', Record<never, never>, Record<never, never>>,
    '/management-reviews/List': RouteRecordInfo<'/management-reviews/List', '/management-reviews/List', Record<never, never>, Record<never, never>>,
    '/management-reviews/View': RouteRecordInfo<'/management-reviews/View', '/management-reviews/View', Record<never, never>, Record<never, never>>,
    '/nomenclature/ConfigurationList': RouteRecordInfo<'/nomenclature/ConfigurationList', '/nomenclature/ConfigurationList', Record<never, never>, Record<never, never>>,
    '/PricingPage': RouteRecordInfo<'/PricingPage', '/PricingPage', Record<never, never>, Record<never, never>>,
    '/PrivacyPolicyPage': RouteRecordInfo<'/PrivacyPolicyPage', '/PrivacyPolicyPage', Record<never, never>, Record<never, never>>,
    '/public/EvaluationForm': RouteRecordInfo<'/public/EvaluationForm', '/public/EvaluationForm', Record<never, never>, Record<never, never>>,
    '/qr-verify': RouteRecordInfo<'/qr-verify', '/qr-verify', Record<never, never>, Record<never, never>>,
    '/stakeholders/Form': RouteRecordInfo<'/stakeholders/Form', '/stakeholders/Form', Record<never, never>, Record<never, never>>,
    '/stakeholders/List': RouteRecordInfo<'/stakeholders/List', '/stakeholders/List', Record<never, never>, Record<never, never>>,
    '/stakeholders/View': RouteRecordInfo<'/stakeholders/View', '/stakeholders/View', Record<never, never>, Record<never, never>>,
    '/support/': RouteRecordInfo<'/support/', '/support', Record<never, never>, Record<never, never>>,
    '/support/communication': RouteRecordInfo<'/support/communication', '/support/communication', Record<never, never>, Record<never, never>>,
    '/support/information-documentee': RouteRecordInfo<'/support/information-documentee', '/support/information-documentee', Record<never, never>, Record<never, never>>,
    '/support/ressources': RouteRecordInfo<'/support/ressources', '/support/ressources', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/403.vue': {
      routes: '/403'
      views: never
    }
    'src/pages/auth/components/email-verification/EmailVerificationActions.vue': {
      routes: '/auth/components/email-verification/EmailVerificationActions'
      views: never
    }
    'src/pages/auth/components/email-verification/EmailVerificationHeader.vue': {
      routes: '/auth/components/email-verification/EmailVerificationHeader'
      views: never
    }
    'src/pages/auth/components/email-verification-result/EmailVerificationFailedCard.vue': {
      routes: '/auth/components/email-verification-result/EmailVerificationFailedCard'
      views: never
    }
    'src/pages/auth/components/email-verification-result/EmailVerificationFailedHeader.vue': {
      routes: '/auth/components/email-verification-result/EmailVerificationFailedHeader'
      views: never
    }
    'src/pages/auth/components/email-verification-result/EmailVerificationSuccessCard.vue': {
      routes: '/auth/components/email-verification-result/EmailVerificationSuccessCard'
      views: never
    }
    'src/pages/auth/components/email-verification-result/EmailVerificationSuccessHeader.vue': {
      routes: '/auth/components/email-verification-result/EmailVerificationSuccessHeader'
      views: never
    }
    'src/pages/auth/components/email-verification-result/EmailVerificationTipCard.vue': {
      routes: '/auth/components/email-verification-result/EmailVerificationTipCard'
      views: never
    }
    'src/pages/auth/components/forgot-password/ForgotPasswordForm.vue': {
      routes: '/auth/components/forgot-password/ForgotPasswordForm'
      views: never
    }
    'src/pages/auth/components/forgot-password/ForgotPasswordSuccess.vue': {
      routes: '/auth/components/forgot-password/ForgotPasswordSuccess'
      views: never
    }
    'src/pages/auth/components/LoginBrandingPanel.vue': {
      routes: '/auth/components/LoginBrandingPanel'
      views: never
    }
    'src/pages/auth/components/LoginDemoAccounts.vue': {
      routes: '/auth/components/LoginDemoAccounts'
      views: never
    }
    'src/pages/auth/components/reset-password/ResetPasswordBrand.vue': {
      routes: '/auth/components/reset-password/ResetPasswordBrand'
      views: never
    }
    'src/pages/auth/components/reset-password/ResetPasswordVisual.vue': {
      routes: '/auth/components/reset-password/ResetPasswordVisual'
      views: never
    }
    'src/pages/auth/components/signup-clientb/SignupHeader.vue': {
      routes: '/auth/components/signup-clientb/SignupHeader'
      views: never
    }
    'src/pages/auth/components/signup-clientb/SignupHelpCard.vue': {
      routes: '/auth/components/signup-clientb/SignupHelpCard'
      views: never
    }
    'src/pages/auth/components/signup-clientb/SignupTerms.vue': {
      routes: '/auth/components/signup-clientb/SignupTerms'
      views: never
    }
    'src/pages/auth/components/signup-status/PendingApprovalCard.vue': {
      routes: '/auth/components/signup-status/PendingApprovalCard'
      views: never
    }
    'src/pages/auth/components/signup-status/SignupLoadingCard.vue': {
      routes: '/auth/components/signup-status/SignupLoadingCard'
      views: never
    }
    'src/pages/auth/components/signup-status/SignupSuccessCard.vue': {
      routes: '/auth/components/signup-status/SignupSuccessCard'
      views: never
    }
    'src/pages/auth/components/signup-status/SignupSuccessHeader.vue': {
      routes: '/auth/components/signup-status/SignupSuccessHeader'
      views: never
    }
    'src/pages/auth/components/SignupCompanyHeader.vue': {
      routes: '/auth/components/SignupCompanyHeader'
      views: never
    }
    'src/pages/auth/components/SignupCompanyTerms.vue': {
      routes: '/auth/components/SignupCompanyTerms'
      views: never
    }
    'src/pages/auth/components/SignupLandingHeader.vue': {
      routes: '/auth/components/SignupLandingHeader'
      views: never
    }
    'src/pages/auth/components/SignupLoginLink.vue': {
      routes: '/auth/components/SignupLoginLink'
      views: never
    }
    'src/pages/auth/email-verification-failed.vue': {
      routes: '/auth/email-verification-failed'
      views: never
    }
    'src/pages/auth/email-verified.vue': {
      routes: '/auth/email-verified'
      views: never
    }
    'src/pages/auth/EmailVerification.vue': {
      routes: '/auth/EmailVerification'
      views: never
    }
    'src/pages/auth/ForcePasswordChange.vue': {
      routes: '/auth/ForcePasswordChange'
      views: never
    }
    'src/pages/auth/forgot-password.vue': {
      routes: '/auth/forgot-password'
      views: never
    }
    'src/pages/auth/ForgotPassword.vue': {
      routes: '/auth/ForgotPassword'
      views: never
    }
    'src/pages/auth/Login.vue': {
      routes: '/auth/Login'
      views: never
    }
    'src/pages/auth/LoginModern.vue': {
      routes: '/auth/LoginModern'
      views: never
    }
    'src/pages/auth/ModernLogin.vue': {
      routes: '/auth/ModernLogin'
      views: never
    }
    'src/pages/auth/OAuthCallback.vue': {
      routes: '/auth/OAuthCallback'
      views: never
    }
    'src/pages/auth/pending-approval.vue': {
      routes: '/auth/pending-approval'
      views: never
    }
    'src/pages/auth/reset-password.vue': {
      routes: '/auth/reset-password'
      views: never
    }
    'src/pages/auth/signup/clientb.vue': {
      routes: '/auth/signup/clientb'
      views: never
    }
    'src/pages/auth/signup/company-old-backup.vue': {
      routes: '/auth/signup/company-old-backup'
      views: never
    }
    'src/pages/auth/signup/CompanySignupModern.vue': {
      routes: '/auth/signup/CompanySignupModern'
      views: never
    }
    'src/pages/auth/signup/individual.vue': {
      routes: '/auth/signup/individual'
      views: never
    }
    'src/pages/auth/signup/individual-new.vue': {
      routes: '/auth/signup/individual-new'
      views: never
    }
    'src/pages/auth/Signup.vue': {
      routes: '/auth/Signup'
      views: never
    }
    'src/pages/auth/signup-loading.vue': {
      routes: '/auth/signup-loading'
      views: never
    }
    'src/pages/auth/signup-success.vue': {
      routes: '/auth/signup-success'
      views: never
    }
    'src/pages/auth/SignupClientA.vue': {
      routes: '/auth/SignupClientA'
      views: never
    }
    'src/pages/auth/SignupClientB.vue': {
      routes: '/auth/SignupClientB'
      views: never
    }
    'src/pages/contexts/Form.vue': {
      routes: '/contexts/Form'
      views: never
    }
    'src/pages/contexts/List.vue': {
      routes: '/contexts/List'
      views: never
    }
    'src/pages/contexts/View.vue': {
      routes: '/contexts/View'
      views: never
    }
    'src/pages/demo-ui.vue': {
      routes: '/demo-ui'
      views: never
    }
    'src/pages/documents/index.vue': {
      routes: '/documents/'
      views: never
    }
    'src/pages/documents/[id].vue': {
      routes: '/documents/[id]'
      views: never
    }
    'src/pages/documents/CodeApproval.vue': {
      routes: '/documents/CodeApproval'
      views: never
    }
    'src/pages/documents/CodeRecycling.vue': {
      routes: '/documents/CodeRecycling'
      views: never
    }
    'src/pages/documents/CodeVerification.vue': {
      routes: '/documents/CodeVerification'
      views: never
    }
    'src/pages/documents/DocumentImport.vue': {
      routes: '/documents/DocumentImport'
      views: never
    }
    'src/pages/documents/WorkflowDashboard.vue': {
      routes: '/documents/WorkflowDashboard'
      views: never
    }
    'src/pages/GuideUtilisationPage.vue': {
      routes: '/GuideUtilisationPage'
      views: never
    }
    'src/pages/improvement/index.vue': {
      routes: '/improvement/'
      views: never
    }
    'src/pages/improvement/actions/index.vue': {
      routes: '/improvement/actions/'
      views: never
    }
    'src/pages/improvement/actions/[id].vue': {
      routes: '/improvement/actions/[id]'
      views: never
    }
    'src/pages/improvement/actions/detail.vue': {
      routes: '/improvement/actions/detail'
      views: never
    }
    'src/pages/improvement/actions/index-new.vue': {
      routes: '/improvement/actions/index-new'
      views: never
    }
    'src/pages/improvement/audits/index.vue': {
      routes: '/improvement/audits/'
      views: never
    }
    'src/pages/improvement/audits/[id].vue': {
      routes: '/improvement/audits/[id]'
      views: never
    }
    'src/pages/improvement/dashboard.vue': {
      routes: '/improvement/dashboard'
      views: never
    }
    'src/pages/improvement/kpi/index.vue': {
      routes: '/improvement/kpi/'
      views: never
    }
    'src/pages/improvement/kpi/dashboard.vue': {
      routes: '/improvement/kpi/dashboard'
      views: never
    }
    'src/pages/improvement/non-conformities/index.vue': {
      routes: '/improvement/non-conformities/'
      views: never
    }
    'src/pages/improvement/non-conformities/[id].vue': {
      routes: '/improvement/non-conformities/[id]'
      views: never
    }
    'src/pages/improvement/objectives/index.vue': {
      routes: '/improvement/objectives/'
      views: never
    }
    'src/pages/improvement/performance/audits-internes.vue': {
      routes: '/improvement/performance/audits-internes'
      views: never
    }
    'src/pages/improvement/performance/dashboard.vue': {
      routes: '/improvement/performance/dashboard'
      views: never
    }
    'src/pages/improvement/performance/revue-direction.vue': {
      routes: '/improvement/performance/revue-direction'
      views: never
    }
    'src/pages/improvement/performance/surveillance.vue': {
      routes: '/improvement/performance/surveillance'
      views: never
    }
    'src/pages/improvement/reclamations/index.vue': {
      routes: '/improvement/reclamations/'
      views: never
    }
    'src/pages/improvement/risks/index.vue': {
      routes: '/improvement/risks/'
      views: never
    }
    'src/pages/iso/energie/consommations.vue': {
      routes: '/iso/energie/consommations'
      views: never
    }
    'src/pages/iso/energie/ipe.vue': {
      routes: '/iso/energie/ipe'
      views: never
    }
    'src/pages/iso/environnement/aspects.vue': {
      routes: '/iso/environnement/aspects'
      views: never
    }
    'src/pages/iso/environnement/obligations.vue': {
      routes: '/iso/environnement/obligations'
      views: never
    }
    'src/pages/iso/leadership/JobDescriptions.vue': {
      routes: '/iso/leadership/JobDescriptions'
      views: never
    }
    'src/pages/iso/leadership/OrgChart.vue': {
      routes: '/iso/leadership/OrgChart'
      views: never
    }
    'src/pages/iso/leadership/Policy.vue': {
      routes: '/iso/leadership/Policy'
      views: never
    }
    'src/pages/iso/planning/ActionPlans.vue': {
      routes: '/iso/planning/ActionPlans'
      views: never
    }
    'src/pages/iso/planning/components/ActionPlansHero.vue': {
      routes: '/iso/planning/components/ActionPlansHero'
      views: never
    }
    'src/pages/iso/planning/components/ActionPlansInfoBanner.vue': {
      routes: '/iso/planning/components/ActionPlansInfoBanner'
      views: never
    }
    'src/pages/iso/planning/components/ActionPlansMetrics.vue': {
      routes: '/iso/planning/components/ActionPlansMetrics'
      views: never
    }
    'src/pages/iso/planning/components/ActionPlansNote.vue': {
      routes: '/iso/planning/components/ActionPlansNote'
      views: never
    }
    'src/pages/iso/planning/components/ActionPlansTable.vue': {
      routes: '/iso/planning/components/ActionPlansTable'
      views: never
    }
    'src/pages/iso/planning/Objectives.vue': {
      routes: '/iso/planning/Objectives'
      views: never
    }
    'src/pages/iso/planning/RisksOpportunities.vue': {
      routes: '/iso/planning/RisksOpportunities'
      views: never
    }
    'src/pages/iso/securite/epi.vue': {
      routes: '/iso/securite/epi'
      views: never
    }
    'src/pages/iso/securite/habilitations.vue': {
      routes: '/iso/securite/habilitations'
      views: never
    }
    'src/pages/iso/securite/vgp.vue': {
      routes: '/iso/securite/vgp'
      views: never
    }
    'src/pages/iso/support/Communication.vue': {
      routes: '/iso/support/Communication'
      views: never
    }
    'src/pages/iso/support/Equipment.vue': {
      routes: '/iso/support/Equipment'
      views: never
    }
    'src/pages/kyc/DocumentUpload.vue': {
      routes: '/kyc/DocumentUpload'
      views: never
    }
    'src/pages/kyc/Pending.vue': {
      routes: '/kyc/Pending'
      views: never
    }
    'src/pages/kyc/ValidationPending.vue': {
      routes: '/kyc/ValidationPending'
      views: never
    }
    'src/pages/landing/components/LandingFooter.vue': {
      routes: '/landing/components/LandingFooter'
      views: never
    }
    'src/pages/landing/components/LandingNavbar.vue': {
      routes: '/landing/components/LandingNavbar'
      views: never
    }
    'src/pages/LandingPage.vue': {
      routes: '/LandingPage'
      views: never
    }
    'src/pages/LockScreen.vue': {
      routes: '/LockScreen'
      views: never
    }
    'src/pages/management-reviews/Form.vue': {
      routes: '/management-reviews/Form'
      views: never
    }
    'src/pages/management-reviews/List.vue': {
      routes: '/management-reviews/List'
      views: never
    }
    'src/pages/management-reviews/View.vue': {
      routes: '/management-reviews/View'
      views: never
    }
    'src/pages/nomenclature/ConfigurationList.vue': {
      routes: '/nomenclature/ConfigurationList'
      views: never
    }
    'src/pages/PricingPage.vue': {
      routes: '/PricingPage'
      views: never
    }
    'src/pages/PrivacyPolicyPage.vue': {
      routes: '/PrivacyPolicyPage'
      views: never
    }
    'src/pages/public/EvaluationForm.vue': {
      routes: '/public/EvaluationForm'
      views: never
    }
    'src/pages/qr-verify.vue': {
      routes: '/qr-verify'
      views: never
    }
    'src/pages/stakeholders/Form.vue': {
      routes: '/stakeholders/Form'
      views: never
    }
    'src/pages/stakeholders/List.vue': {
      routes: '/stakeholders/List'
      views: never
    }
    'src/pages/stakeholders/View.vue': {
      routes: '/stakeholders/View'
      views: never
    }
    'src/pages/support/index.vue': {
      routes: '/support/'
      views: never
    }
    'src/pages/support/communication.vue': {
      routes: '/support/communication'
      views: never
    }
    'src/pages/support/information-documentee.vue': {
      routes: '/support/information-documentee'
      views: never
    }
    'src/pages/support/ressources.vue': {
      routes: '/support/ressources'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
